services:
  postgres:
    platform: linux/arm64

  app:
    platform: linux/arm64
    image: ${YOMU_IMAGE:-ghcr.io/emmanuelsalazar92/yomu:apple-silicon}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
