ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'ENGLISH_CASE_MATCH';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'ENGLISH_VOCABULARY';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'ENGLISH_INITIAL_SOUND';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'ENGLISH_CVC_BUILD';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'ENGLISH_SIGHT_WORD';
