ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_NUMBER_QUANTITY';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_COUNT_OBJECTS';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_COMPARE_QUANTITIES';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_NUMBER_SEQUENCE';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_ADDITION';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_SUBTRACTION';
