ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_PLACE_VALUE';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_COMPARE_TWO_DIGIT';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_ADDITION_TWO_DIGIT';
ALTER TYPE "LearningActivityType" ADD VALUE IF NOT EXISTS 'MATH_SUBTRACTION_TWO_DIGIT';
